enum ScreenMainType {
  SCREEN_MAIN_SITE_SYNC = 'SCREEN_MAIN_SITE_SYNC',
  SCREEN_MAIN_SITE_UPDATE = 'SCREEN_MAIN_SITE_UPDATE',
  SCREEN_MAIN_DASHBOARD = 'SCREEN_MAIN_DASHBOARD',
  SCREEN_MAIN_TRENDS = 'SCREEN_MAIN_TRENDS',
  SCREEN_MAIN_MESSAGES = 'SCREEN_MAIN_MESSAGES',
  SCREEN_MAIN_SETTING = 'SCREEN_MAIN_SETTING',
}

export default ScreenMainType;
