enum ScreenAuthType {
  SCREEN_AUTH_LOGIN = 'SCREEN_AUTH_LOGIN',
  SCREEN_AUTH_SIGNUP_PROFILE = 'SCREEN_AUTH_SIGNUP_PROFILE',
  SCREEN_AUTH_SIGNUP_SURVEY = 'SCREEN_AUTH_SIGNUP_SURVEY',
  SCREEN_AUTH_SIGNUP_UTILITY = 'SCREEN_AUTH_SIGNUP_UTILITY',
  SCREEN_AUTH_TERMS = 'SCREEN_AUTH_TERMS',
}

export default ScreenAuthType;
